### ISSUE TITLE
Corrigir Índices na criação das tabelas

### ISSUE THREAD

**Issue by GabrielGuinzani** [guilherme-savio/SeguroImoveis#12]
Corrigir os índices nos scripts de criação das tabelas com base no dicionário de dados

**Comment by dufrtss** [comment]
Incluído no Script de criação das tabelas a criação dos indíces de acordo com o dicionário de dados. Confiram antes de encerrar a issue.

**Comment by dufrtss** [comment]
Adaptar os indexes para serem compatíveis com o MySQL 8.0
