### ISSUE TITLE
Atualizar dicionário de dados

### ISSUE THREAD

**Issue by Bruno-Venturini** [guilherme-savio/SeguroImoveis#6]
Necessário finalizar o dicionário de dados comportando todas as tabelas existentes no banco.

**Comment by GabrielGuinzani** [comment]
Atualizadas tabelas Apolice, Imovel, Avaliacao

**Comment by GabrielGuinzani** [comment]
Atualizadas tabelas Apolice_Cobertura, Cobertura e Sinistro

**Comment by dufrtss** [comment]
Adicionada a tabela Cliente no dicionário de dados!

**Comment by GabrielGuinzani** [comment]
Corrigidos Alguns Errinhos no Dicionário

**Comment by SofiaMartinslv** [comment]
Adicionada a última tabela do dicionário, a Pagamento.

**Comment by SofiaMartinslv** [comment]
Dicionário finalizado.
