### ISSUE TITLE
Criar procedure referente ao relatório.

### ISSUE THREAD

**Issue by Bruno-Venturini** [guilherme-savio/SeguroImoveis#7]
Necessário criar uma procedure para gerar relatório com as seguintes informações: 

Nome do cliente, data da apólice, data do fim e valor da apólice, código do imóvel, se possui sinistro ou não, tipo de cobertura da apólice e se está vigente ou não.

**Comment by Bruno-Venturini** [comment]
Lembrando que é necessário ser possível filtrar por data.

**Comment by angelum23** [comment]
Feito no  bd.sql
