### ISSUE TITLE
Criar 5 consultas referentes ao sistema.

### ISSUE THREAD

**Issue by Bruno-Venturini** [guilherme-savio/SeguroImoveis#8]
Necessário criar 5 consultas criativas referentes ao nosso sistema. Favor comentar acima da consulta a sua funcionalidade.

**Comment by guilherme-savio** [comment]
Olá, 

Considere 1 das 5 consultas elaboradas. (Consulta sinistros por tipo de imóvel e valor médio de sinistro.)

**Comment by Bruno-Venturini** [comment]
Interassente inserir todas as consultas no mesmo arquivo (/scripts/selects.sql). Não esqueçam de explicar a funcionalidade.

**Comment by GabrielGuinzani** [comment]
> Interassente inserir todas as consultas no mesmo arquivo (/scripts/selects.sql). Não esqueçam de explicar a funcionalidade.

Segunda consulta feita, adicionei uma consulta de pagamentos atrasados por apólice, expliquei a funcionalidade no arquivo

**Comment by dufrtss** [comment]
Criado a consulta de número 3: Consulta de apólices com coberturas abrangentes no ./scripts/selects.sql

**Comment by SofiaMartinslv** [comment]
Quarta consulta feita: Consulta de média de avaliação por tipo de imóvel

**Comment by guga2905** [comment]
Quinta consulta feita: Consulta de pagamentos atrasados por apólice

**Comment by Bruno-Venturini** [comment]
@guga2905 Favor olhar novamente as consultas. Parece que você inseriu uma consulta que já existia no arquivo.

**Comment by guga2905** [comment]
Alterado a quinta consulta para: Consulta de valor total de sinistros por mês

**Comment by Bruno-Venturini** [comment]
Muito bom! todas as perguntas foram concluídas.

Considerem resolvido.
